-- ============================================================
-- Looker Studio Views
-- ============================================================
-- Simple views for connecting to Looker Studio
-- 4 data sources for dashboards
-- ============================================================

-- 1. Individual Dentists (261K)
CREATE OR REPLACE VIEW CLEAN.V_INDIVIDUAL_DENTISTS AS
SELECT 
    NPI,
    DISPLAY_NAME,
    FIRST_NAME,
    LAST_NAME,
    CREDENTIAL,
    PRACTICE_ADDRESS_FULL AS ADDRESS,
    PRACTICE_CITY AS CITY,
    PRACTICE_STATE AS STATE,
    PRACTICE_ZIP AS ZIP,
    PRACTICE_PHONE_CLEAN AS PHONE,
    PRIMARY_TAXONOMY_CODE AS TAXONOMY_CODE,
    GENDER,
    PRACTICE_AGE_COHORT,
    ENUMERATION_DATE,
    CREATED_AT
FROM CLEAN.DENTAL_PROVIDERS
WHERE ENTITY_TYPE = 'Individual';

-- 2. Organizations (105K)
CREATE OR REPLACE VIEW CLEAN.V_ORGANIZATIONS AS
SELECT 
    NPI,
    ORGANIZATION_NAME,
    DBA_NAME,
    PRACTICE_ADDRESS_FULL AS ADDRESS,
    PRACTICE_CITY AS CITY,
    PRACTICE_STATE AS STATE,
    PRACTICE_ZIP AS ZIP,
    PRACTICE_PHONE_CLEAN AS PHONE,
    PRIMARY_TAXONOMY_CODE AS TAXONOMY_CODE,
    AUTH_OFFICIAL_FULL_NAME,
    AUTH_OFFICIAL_CREDENTIAL,
    AUTH_OFFICIAL_PHONE,
    PRACTICE_AGE_COHORT,
    ENUMERATION_DATE,
    CREATED_AT
FROM CLEAN.DENTAL_PROVIDERS
WHERE ENTITY_TYPE = 'Organization';

-- 3. Decision Makers - Dentist Practice Owners (66K)
CREATE OR REPLACE VIEW CLEAN.V_DECISION_MAKERS AS
SELECT 
    ORGANIZATION_NPI,
    ORGANIZATION_NAME,
    DBA_NAME,
    ORG_ADDRESS,
    ORG_CITY,
    ORG_STATE,
    ORG_ZIP,
    ORG_PHONE,
    INDIVIDUAL_NPI AS OWNER_NPI,
    DENTIST_NAME AS OWNER_NAME,
    FIRST_NAME AS OWNER_FIRST_NAME,
    LAST_NAME AS OWNER_LAST_NAME,
    DENTIST_CREDENTIAL AS OWNER_CREDENTIAL,
    GENDER AS OWNER_GENDER,
    DENTIST_PHONE AS OWNER_PHONE,
    DENTIST_TAXONOMY AS OWNER_TAXONOMY,
    MATCH_CONFIDENCE,
    PRACTICE_AGE_COHORT,
    CREATED_AT
FROM CLEAN.PRACTICE_DECISION_MAKERS;

-- 4. Auth Officials to Enrich (38K)
CREATE OR REPLACE VIEW CLEAN.V_AUTH_OFFICIALS AS
SELECT 
    ORGANIZATION_NPI,
    ORGANIZATION_NAME,
    DBA_NAME,
    PRACTICE_ADDRESS_1 AS ADDRESS,
    PRACTICE_CITY AS CITY,
    PRACTICE_STATE AS STATE,
    PRACTICE_ZIP AS ZIP,
    AUTH_OFFICIAL_FULL_NAME,
    AUTH_OFFICIAL_FIRST_NAME,
    AUTH_OFFICIAL_LAST_NAME,
    AUTH_OFFICIAL_CREDENTIAL,
    AUTH_OFFICIAL_PHONE,
    CREDENTIAL_CATEGORY,
    ENRICHMENT_PRIORITY,
    ENRICHED_EMAIL,
    ENRICHED_LINKEDIN_URL,
    ENRICHED_TITLE,
    INFERRED_ROLE,
    ENRICHMENT_SOURCE,
    ENRICHED_AT,
    CASE 
        WHEN ENRICHED_EMAIL IS NOT NULL THEN 'Enriched'
        ELSE 'Pending'
    END AS ENRICHMENT_STATUS,
    CREATED_AT
FROM CLEAN.AUTH_OFFICIALS_TO_ENRICH;

-- Grant access to Looker role
GRANT SELECT ON CLEAN.V_INDIVIDUAL_DENTISTS TO ROLE LOOKER_ROLE;
GRANT SELECT ON CLEAN.V_ORGANIZATIONS TO ROLE LOOKER_ROLE;
GRANT SELECT ON CLEAN.V_DECISION_MAKERS TO ROLE LOOKER_ROLE;
GRANT SELECT ON CLEAN.V_AUTH_OFFICIALS TO ROLE LOOKER_ROLE;

